/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Monster.def
	public class EntityBaseEntityCall_MonsterBase : EntityCall
	{

		public EntityBaseEntityCall_MonsterBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_MonsterBase : EntityCall
	{

		public EntityCellEntityCall_MonsterBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void clientRequestUseSkill(UInt32 arg1, Int32 arg2)
		{
			Bundle pBundle = newCall("clientRequestUseSkill", 0);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeInt32(arg2);
			sendCall(null);
		}

		public void skillNodeCallServer(UInt32 arg1, Int32 arg2, TABLE arg3)
		{
			Bundle pBundle = newCall("skillNodeCallServer", 0);
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			bundle.writeInt32(arg2);
			((DATATYPE_TABLE)EntityDef.id2datatypes[33]).addToStreamEx(bundle, arg3);
			sendCall(null);
		}

	}
	}
