/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Monster : MonsterBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Monster.def
	// Please inherit and implement "class Monster : MonsterBase"
	public abstract class MonsterBase : Entity
	{
		public EntityBaseEntityCall_MonsterBase baseEntityCall = null;
		public EntityCellEntityCall_MonsterBase cellEntityCall = null;

		public Int32 HP = 0;
		public virtual void onHPChanged(Int32 oldValue) {}
		public Int32 HP_Max = 0;
		public virtual void onHP_MaxChanged(Int32 oldValue) {}
		public Int32 MP = 0;
		public virtual void onMPChanged(Int32 oldValue) {}
		public Int32 MP_Max = 0;
		public virtual void onMP_MaxChanged(Int32 oldValue) {}
		public PATH_POINTS aiMoviePath = new PATH_POINTS();
		public virtual void onAiMoviePathChanged(PATH_POINTS oldValue) {}
		public UInt32 aiMoviePathIndex = 0;
		public virtual void onAiMoviePathIndexChanged(UInt32 oldValue) {}
		public Vector3 aiMovieToPoint = new Vector3(0f, 0f, 0f);
		public virtual void onAiMovieToPointChanged(Vector3 oldValue) {}
		public UInt32 aiMovingType = 0;
		public virtual void onAiMovingTypeChanged(UInt32 oldValue) {}
		public float confirmTime = 0f;
		public virtual void onConfirmTimeChanged(float oldValue) {}
		public Int32 controlId = 0;
		public virtual void onControlIdChanged(Int32 oldValue) {}
		public UInt32 entityNO = 0;
		public virtual void onEntityNOChanged(UInt32 oldValue) {}
		public Int32 forbids = 0;
		public virtual void onForbidsChanged(Int32 oldValue) {}
		public Byte inBattle = 0;
		public virtual void onInBattleChanged(Byte oldValue) {}
		public UInt32 modelID = 0;
		public virtual void onModelIDChanged(UInt32 oldValue) {}
		public Byte modelScale = 30;
		public virtual void onModelScaleChanged(Byte oldValue) {}
		public Vector3 moveDirection = new Vector3(0f, 0f, 0f);
		public virtual void onMoveDirectionChanged(Vector3 oldValue) {}
		public MOVE_INFOS moveInfo = new MOVE_INFOS();
		public virtual void onMoveInfoChanged(MOVE_INFOS oldValue) {}
		public float moveSpeed = 0f;
		public virtual void onMoveSpeedChanged(float oldValue) {}
		public UInt32 moveType = 0;
		public virtual void onMoveTypeChanged(UInt32 oldValue) {}
		public string name = "";
		public virtual void onNameChanged(string oldValue) {}
		public SByte state = 0;
		public virtual void onStateChanged(SByte oldValue) {}
		public Byte subState = 0;
		public virtual void onSubStateChanged(Byte oldValue) {}
		public Int32 targetID = 0;
		public virtual void onTargetIDChanged(Int32 oldValue) {}
		public UInt32 uid = 0;
		public virtual void onUidChanged(UInt32 oldValue) {}
		public UInt32 utype = 0;
		public virtual void onUtypeChanged(UInt32 oldValue) {}

		public abstract void chaseTarget(Int32 arg1); 
		public abstract void confirmMoveTimeStamp(float arg1); 
		public abstract void fightMove(SByte arg1, Vector3 arg2); 
		public abstract void randomWalk(); 
		public abstract void recvDamage(Int32 arg1, Int32 arg2, Int32 arg3, Int32 arg4); 
		public abstract void serverRequestUseSkill(UInt32 arg1, Int32 arg2); 
		public abstract void serverSkillFinish(Int32 arg1); 
		public abstract void skillNodeCallClient(UInt32 arg1, Int32 arg2, TABLE arg3); 
		public abstract void startP3ClientMove(float arg1); 
		public abstract void stopMotion(); 
		public abstract void stopP3ClientMove(float arg1); 
		public abstract void useSkill(Int32 arg1, Int32 arg2); 

		public MonsterBase()
		{
		}

		public override void onComponentsEnterworld()
		{
		}

		public override void onComponentsLeaveworld()
		{
		}

		public override void onGetBase()
		{
			baseEntityCall = new EntityBaseEntityCall_MonsterBase(id, className);
		}

		public override void onGetCell()
		{
			cellEntityCall = new EntityCellEntityCall_MonsterBase(id, className);
		}

		public override void onLoseCell()
		{
			cellEntityCall = null;
		}

		public override EntityCall getBaseEntityCall()
		{
			return baseEntityCall;
		}

		public override EntityCall getCellEntityCall()
		{
			return cellEntityCall;
		}

		public override void attachComponents()
		{
		}

		public override void detachComponents()
		{
		}

		public override void onRemoteMethodCall(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Monster"];

			UInt16 methodUtype = 0;
			UInt16 componentPropertyUType = 0;

			if(sm.usePropertyDescrAlias)
			{
				componentPropertyUType = stream.readUint8();
			}
			else
			{
				componentPropertyUType = stream.readUint16();
			}

			if(sm.useMethodDescrAlias)
			{
				methodUtype = stream.readUint8();
			}
			else
			{
				methodUtype = stream.readUint16();
			}

			Method method = null;

			if(componentPropertyUType == 0)
			{
				method = sm.idmethods[methodUtype];
			}
			else
			{
				Property pComponentPropertyDescription = sm.idpropertys[componentPropertyUType];
				switch(pComponentPropertyDescription.properUtype)
				{
					default:
						break;
				}

				return;
			}

			switch(method.methodUtype)
			{
				case 63:
					Int32 chaseTarget_arg1 = stream.readInt32();
					chaseTarget(chaseTarget_arg1);
					break;
				case 73:
					float confirmMoveTimeStamp_arg1 = stream.readFloat();
					confirmMoveTimeStamp(confirmMoveTimeStamp_arg1);
					break;
				case 66:
					SByte fightMove_arg1 = stream.readInt8();
					Vector3 fightMove_arg2 = stream.readVector3();
					fightMove(fightMove_arg1, fightMove_arg2);
					break;
				case 62:
					randomWalk();
					break;
				case 51:
					Int32 recvDamage_arg1 = stream.readInt32();
					Int32 recvDamage_arg2 = stream.readInt32();
					Int32 recvDamage_arg3 = stream.readInt32();
					Int32 recvDamage_arg4 = stream.readInt32();
					recvDamage(recvDamage_arg1, recvDamage_arg2, recvDamage_arg3, recvDamage_arg4);
					break;
				case 53:
					UInt32 serverRequestUseSkill_arg1 = stream.readUint32();
					Int32 serverRequestUseSkill_arg2 = stream.readInt32();
					serverRequestUseSkill(serverRequestUseSkill_arg1, serverRequestUseSkill_arg2);
					break;
				case 54:
					Int32 serverSkillFinish_arg1 = stream.readInt32();
					serverSkillFinish(serverSkillFinish_arg1);
					break;
				case 52:
					UInt32 skillNodeCallClient_arg1 = stream.readUint32();
					Int32 skillNodeCallClient_arg2 = stream.readInt32();
					TABLE skillNodeCallClient_arg3 = ((DATATYPE_TABLE)method.args[2]).createFromStreamEx(stream);
					skillNodeCallClient(skillNodeCallClient_arg1, skillNodeCallClient_arg2, skillNodeCallClient_arg3);
					break;
				case 74:
					float startP3ClientMove_arg1 = stream.readFloat();
					startP3ClientMove(startP3ClientMove_arg1);
					break;
				case 65:
					stopMotion();
					break;
				case 75:
					float stopP3ClientMove_arg1 = stream.readFloat();
					stopP3ClientMove(stopP3ClientMove_arg1);
					break;
				case 64:
					Int32 useSkill_arg1 = stream.readInt32();
					Int32 useSkill_arg2 = stream.readInt32();
					useSkill(useSkill_arg1, useSkill_arg2);
					break;
				default:
					break;
			};
		}

		public override void onUpdatePropertys(MemoryStream stream)
		{
			ScriptModule sm = EntityDef.moduledefs["Monster"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			while(stream.length() > 0)
			{
				UInt16 _t_utype = 0;
				UInt16 _t_child_utype = 0;

				{
					if(sm.usePropertyDescrAlias)
					{
						_t_utype = stream.readUint8();
						_t_child_utype = stream.readUint8();
					}
					else
					{
						_t_utype = stream.readUint16();
						_t_child_utype = stream.readUint16();
					}
				}

				Property prop = null;

				if(_t_utype == 0)
				{
					prop = pdatas[_t_child_utype];
				}
				else
				{
					Property pComponentPropertyDescription = pdatas[_t_utype];
					switch(pComponentPropertyDescription.properUtype)
					{
						default:
							break;
					}

					return;
				}

				switch(prop.properUtype)
				{
					case 47001:
						Int32 oldval_HP = HP;
						HP = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onHPChanged(oldval_HP);
						}
						else
						{
							if(inWorld)
								onHPChanged(oldval_HP);
						}

						break;
					case 47002:
						Int32 oldval_HP_Max = HP_Max;
						HP_Max = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onHP_MaxChanged(oldval_HP_Max);
						}
						else
						{
							if(inWorld)
								onHP_MaxChanged(oldval_HP_Max);
						}

						break;
					case 47003:
						Int32 oldval_MP = MP;
						MP = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMPChanged(oldval_MP);
						}
						else
						{
							if(inWorld)
								onMPChanged(oldval_MP);
						}

						break;
					case 47004:
						Int32 oldval_MP_Max = MP_Max;
						MP_Max = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onMP_MaxChanged(oldval_MP_Max);
						}
						else
						{
							if(inWorld)
								onMP_MaxChanged(oldval_MP_Max);
						}

						break;
					case 43:
						PATH_POINTS oldval_aiMoviePath = aiMoviePath;
						aiMoviePath = ((DATATYPE_PATH_POINTS)EntityDef.id2datatypes[24]).createFromStreamEx(stream);

						if(prop.isBase())
						{
							if(inited)
								onAiMoviePathChanged(oldval_aiMoviePath);
						}
						else
						{
							if(inWorld)
								onAiMoviePathChanged(oldval_aiMoviePath);
						}

						break;
					case 44:
						UInt32 oldval_aiMoviePathIndex = aiMoviePathIndex;
						aiMoviePathIndex = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onAiMoviePathIndexChanged(oldval_aiMoviePathIndex);
						}
						else
						{
							if(inWorld)
								onAiMoviePathIndexChanged(oldval_aiMoviePathIndex);
						}

						break;
					case 42:
						Vector3 oldval_aiMovieToPoint = aiMovieToPoint;
						aiMovieToPoint = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onAiMovieToPointChanged(oldval_aiMovieToPoint);
						}
						else
						{
							if(inWorld)
								onAiMovieToPointChanged(oldval_aiMovieToPoint);
						}

						break;
					case 41:
						UInt32 oldval_aiMovingType = aiMovingType;
						aiMovingType = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onAiMovingTypeChanged(oldval_aiMovingType);
						}
						else
						{
							if(inWorld)
								onAiMovingTypeChanged(oldval_aiMovingType);
						}

						break;
					case 51:
						float oldval_confirmTime = confirmTime;
						confirmTime = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onConfirmTimeChanged(oldval_confirmTime);
						}
						else
						{
							if(inWorld)
								onConfirmTimeChanged(oldval_confirmTime);
						}

						break;
					case 52:
						Int32 oldval_controlId = controlId;
						controlId = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onControlIdChanged(oldval_controlId);
						}
						else
						{
							if(inWorld)
								onControlIdChanged(oldval_controlId);
						}

						break;
					case 40001:
						Vector3 oldval_direction = direction;
						direction = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onDirectionChanged(oldval_direction);
						}
						else
						{
							if(inWorld)
								onDirectionChanged(oldval_direction);
						}

						break;
					case 51007:
						UInt32 oldval_entityNO = entityNO;
						entityNO = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onEntityNOChanged(oldval_entityNO);
						}
						else
						{
							if(inWorld)
								onEntityNOChanged(oldval_entityNO);
						}

						break;
					case 47005:
						Int32 oldval_forbids = forbids;
						forbids = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onForbidsChanged(oldval_forbids);
						}
						else
						{
							if(inWorld)
								onForbidsChanged(oldval_forbids);
						}

						break;
					case 38:
						Byte oldval_inBattle = inBattle;
						inBattle = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onInBattleChanged(oldval_inBattle);
						}
						else
						{
							if(inWorld)
								onInBattleChanged(oldval_inBattle);
						}

						break;
					case 41006:
						UInt32 oldval_modelID = modelID;
						modelID = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onModelIDChanged(oldval_modelID);
						}
						else
						{
							if(inWorld)
								onModelIDChanged(oldval_modelID);
						}

						break;
					case 41007:
						Byte oldval_modelScale = modelScale;
						modelScale = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onModelScaleChanged(oldval_modelScale);
						}
						else
						{
							if(inWorld)
								onModelScaleChanged(oldval_modelScale);
						}

						break;
					case 48:
						Vector3 oldval_moveDirection = moveDirection;
						moveDirection = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onMoveDirectionChanged(oldval_moveDirection);
						}
						else
						{
							if(inWorld)
								onMoveDirectionChanged(oldval_moveDirection);
						}

						break;
					case 49:
						MOVE_INFOS oldval_moveInfo = moveInfo;
						moveInfo = ((DATATYPE_MOVE_INFOS)EntityDef.id2datatypes[33]).createFromStreamEx(stream);

						if(prop.isBase())
						{
							if(inited)
								onMoveInfoChanged(oldval_moveInfo);
						}
						else
						{
							if(inWorld)
								onMoveInfoChanged(oldval_moveInfo);
						}

						break;
					case 50:
						float oldval_moveSpeed = moveSpeed;
						moveSpeed = stream.readFloat();

						if(prop.isBase())
						{
							if(inited)
								onMoveSpeedChanged(oldval_moveSpeed);
						}
						else
						{
							if(inWorld)
								onMoveSpeedChanged(oldval_moveSpeed);
						}

						break;
					case 47:
						UInt32 oldval_moveType = moveType;
						moveType = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onMoveTypeChanged(oldval_moveType);
						}
						else
						{
							if(inWorld)
								onMoveTypeChanged(oldval_moveType);
						}

						break;
					case 41003:
						string oldval_name = name;
						name = stream.readUnicode();

						if(prop.isBase())
						{
							if(inited)
								onNameChanged(oldval_name);
						}
						else
						{
							if(inWorld)
								onNameChanged(oldval_name);
						}

						break;
					case 40000:
						Vector3 oldval_position = position;
						position = stream.readVector3();

						if(prop.isBase())
						{
							if(inited)
								onPositionChanged(oldval_position);
						}
						else
						{
							if(inWorld)
								onPositionChanged(oldval_position);
						}

						break;
					case 40002:
						stream.readUint32();
						break;
					case 47006:
						SByte oldval_state = state;
						state = stream.readInt8();

						if(prop.isBase())
						{
							if(inited)
								onStateChanged(oldval_state);
						}
						else
						{
							if(inWorld)
								onStateChanged(oldval_state);
						}

						break;
					case 47007:
						Byte oldval_subState = subState;
						subState = stream.readUint8();

						if(prop.isBase())
						{
							if(inited)
								onSubStateChanged(oldval_subState);
						}
						else
						{
							if(inWorld)
								onSubStateChanged(oldval_subState);
						}

						break;
					case 40:
						Int32 oldval_targetID = targetID;
						targetID = stream.readInt32();

						if(prop.isBase())
						{
							if(inited)
								onTargetIDChanged(oldval_targetID);
						}
						else
						{
							if(inWorld)
								onTargetIDChanged(oldval_targetID);
						}

						break;
					case 41004:
						UInt32 oldval_uid = uid;
						uid = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onUidChanged(oldval_uid);
						}
						else
						{
							if(inWorld)
								onUidChanged(oldval_uid);
						}

						break;
					case 41005:
						UInt32 oldval_utype = utype;
						utype = stream.readUint32();

						if(prop.isBase())
						{
							if(inited)
								onUtypeChanged(oldval_utype);
						}
						else
						{
							if(inWorld)
								onUtypeChanged(oldval_utype);
						}

						break;
					default:
						break;
				};
			}
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs["Monster"];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Int32 oldval_HP = HP;
			Property prop_HP = pdatas[4];
			if(prop_HP.isBase())
			{
				if(inited && !inWorld)
					onHPChanged(oldval_HP);
			}
			else
			{
				if(inWorld)
				{
					if(prop_HP.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHPChanged(oldval_HP);
					}
				}
			}

			Int32 oldval_HP_Max = HP_Max;
			Property prop_HP_Max = pdatas[5];
			if(prop_HP_Max.isBase())
			{
				if(inited && !inWorld)
					onHP_MaxChanged(oldval_HP_Max);
			}
			else
			{
				if(inWorld)
				{
					if(prop_HP_Max.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onHP_MaxChanged(oldval_HP_Max);
					}
				}
			}

			Int32 oldval_MP = MP;
			Property prop_MP = pdatas[6];
			if(prop_MP.isBase())
			{
				if(inited && !inWorld)
					onMPChanged(oldval_MP);
			}
			else
			{
				if(inWorld)
				{
					if(prop_MP.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMPChanged(oldval_MP);
					}
				}
			}

			Int32 oldval_MP_Max = MP_Max;
			Property prop_MP_Max = pdatas[7];
			if(prop_MP_Max.isBase())
			{
				if(inited && !inWorld)
					onMP_MaxChanged(oldval_MP_Max);
			}
			else
			{
				if(inWorld)
				{
					if(prop_MP_Max.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMP_MaxChanged(oldval_MP_Max);
					}
				}
			}

			PATH_POINTS oldval_aiMoviePath = aiMoviePath;
			Property prop_aiMoviePath = pdatas[8];
			if(prop_aiMoviePath.isBase())
			{
				if(inited && !inWorld)
					onAiMoviePathChanged(oldval_aiMoviePath);
			}
			else
			{
				if(inWorld)
				{
					if(prop_aiMoviePath.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAiMoviePathChanged(oldval_aiMoviePath);
					}
				}
			}

			UInt32 oldval_aiMoviePathIndex = aiMoviePathIndex;
			Property prop_aiMoviePathIndex = pdatas[9];
			if(prop_aiMoviePathIndex.isBase())
			{
				if(inited && !inWorld)
					onAiMoviePathIndexChanged(oldval_aiMoviePathIndex);
			}
			else
			{
				if(inWorld)
				{
					if(prop_aiMoviePathIndex.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAiMoviePathIndexChanged(oldval_aiMoviePathIndex);
					}
				}
			}

			Vector3 oldval_aiMovieToPoint = aiMovieToPoint;
			Property prop_aiMovieToPoint = pdatas[10];
			if(prop_aiMovieToPoint.isBase())
			{
				if(inited && !inWorld)
					onAiMovieToPointChanged(oldval_aiMovieToPoint);
			}
			else
			{
				if(inWorld)
				{
					if(prop_aiMovieToPoint.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAiMovieToPointChanged(oldval_aiMovieToPoint);
					}
				}
			}

			UInt32 oldval_aiMovingType = aiMovingType;
			Property prop_aiMovingType = pdatas[11];
			if(prop_aiMovingType.isBase())
			{
				if(inited && !inWorld)
					onAiMovingTypeChanged(oldval_aiMovingType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_aiMovingType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onAiMovingTypeChanged(oldval_aiMovingType);
					}
				}
			}

			float oldval_confirmTime = confirmTime;
			Property prop_confirmTime = pdatas[12];
			if(prop_confirmTime.isBase())
			{
				if(inited && !inWorld)
					onConfirmTimeChanged(oldval_confirmTime);
			}
			else
			{
				if(inWorld)
				{
					if(prop_confirmTime.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onConfirmTimeChanged(oldval_confirmTime);
					}
				}
			}

			Int32 oldval_controlId = controlId;
			Property prop_controlId = pdatas[13];
			if(prop_controlId.isBase())
			{
				if(inited && !inWorld)
					onControlIdChanged(oldval_controlId);
			}
			else
			{
				if(inWorld)
				{
					if(prop_controlId.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onControlIdChanged(oldval_controlId);
					}
				}
			}

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[2];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			UInt32 oldval_entityNO = entityNO;
			Property prop_entityNO = pdatas[14];
			if(prop_entityNO.isBase())
			{
				if(inited && !inWorld)
					onEntityNOChanged(oldval_entityNO);
			}
			else
			{
				if(inWorld)
				{
					if(prop_entityNO.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onEntityNOChanged(oldval_entityNO);
					}
				}
			}

			Int32 oldval_forbids = forbids;
			Property prop_forbids = pdatas[15];
			if(prop_forbids.isBase())
			{
				if(inited && !inWorld)
					onForbidsChanged(oldval_forbids);
			}
			else
			{
				if(inWorld)
				{
					if(prop_forbids.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onForbidsChanged(oldval_forbids);
					}
				}
			}

			Byte oldval_inBattle = inBattle;
			Property prop_inBattle = pdatas[16];
			if(prop_inBattle.isBase())
			{
				if(inited && !inWorld)
					onInBattleChanged(oldval_inBattle);
			}
			else
			{
				if(inWorld)
				{
					if(prop_inBattle.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onInBattleChanged(oldval_inBattle);
					}
				}
			}

			UInt32 oldval_modelID = modelID;
			Property prop_modelID = pdatas[17];
			if(prop_modelID.isBase())
			{
				if(inited && !inWorld)
					onModelIDChanged(oldval_modelID);
			}
			else
			{
				if(inWorld)
				{
					if(prop_modelID.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onModelIDChanged(oldval_modelID);
					}
				}
			}

			Byte oldval_modelScale = modelScale;
			Property prop_modelScale = pdatas[18];
			if(prop_modelScale.isBase())
			{
				if(inited && !inWorld)
					onModelScaleChanged(oldval_modelScale);
			}
			else
			{
				if(inWorld)
				{
					if(prop_modelScale.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onModelScaleChanged(oldval_modelScale);
					}
				}
			}

			Vector3 oldval_moveDirection = moveDirection;
			Property prop_moveDirection = pdatas[19];
			if(prop_moveDirection.isBase())
			{
				if(inited && !inWorld)
					onMoveDirectionChanged(oldval_moveDirection);
			}
			else
			{
				if(inWorld)
				{
					if(prop_moveDirection.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMoveDirectionChanged(oldval_moveDirection);
					}
				}
			}

			MOVE_INFOS oldval_moveInfo = moveInfo;
			Property prop_moveInfo = pdatas[20];
			if(prop_moveInfo.isBase())
			{
				if(inited && !inWorld)
					onMoveInfoChanged(oldval_moveInfo);
			}
			else
			{
				if(inWorld)
				{
					if(prop_moveInfo.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMoveInfoChanged(oldval_moveInfo);
					}
				}
			}

			float oldval_moveSpeed = moveSpeed;
			Property prop_moveSpeed = pdatas[21];
			if(prop_moveSpeed.isBase())
			{
				if(inited && !inWorld)
					onMoveSpeedChanged(oldval_moveSpeed);
			}
			else
			{
				if(inWorld)
				{
					if(prop_moveSpeed.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMoveSpeedChanged(oldval_moveSpeed);
					}
				}
			}

			UInt32 oldval_moveType = moveType;
			Property prop_moveType = pdatas[22];
			if(prop_moveType.isBase())
			{
				if(inited && !inWorld)
					onMoveTypeChanged(oldval_moveType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_moveType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onMoveTypeChanged(oldval_moveType);
					}
				}
			}

			string oldval_name = name;
			Property prop_name = pdatas[23];
			if(prop_name.isBase())
			{
				if(inited && !inWorld)
					onNameChanged(oldval_name);
			}
			else
			{
				if(inWorld)
				{
					if(prop_name.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onNameChanged(oldval_name);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[1];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			SByte oldval_state = state;
			Property prop_state = pdatas[24];
			if(prop_state.isBase())
			{
				if(inited && !inWorld)
					onStateChanged(oldval_state);
			}
			else
			{
				if(inWorld)
				{
					if(prop_state.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onStateChanged(oldval_state);
					}
				}
			}

			Byte oldval_subState = subState;
			Property prop_subState = pdatas[25];
			if(prop_subState.isBase())
			{
				if(inited && !inWorld)
					onSubStateChanged(oldval_subState);
			}
			else
			{
				if(inWorld)
				{
					if(prop_subState.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onSubStateChanged(oldval_subState);
					}
				}
			}

			Int32 oldval_targetID = targetID;
			Property prop_targetID = pdatas[26];
			if(prop_targetID.isBase())
			{
				if(inited && !inWorld)
					onTargetIDChanged(oldval_targetID);
			}
			else
			{
				if(inWorld)
				{
					if(prop_targetID.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onTargetIDChanged(oldval_targetID);
					}
				}
			}

			UInt32 oldval_uid = uid;
			Property prop_uid = pdatas[27];
			if(prop_uid.isBase())
			{
				if(inited && !inWorld)
					onUidChanged(oldval_uid);
			}
			else
			{
				if(inWorld)
				{
					if(prop_uid.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onUidChanged(oldval_uid);
					}
				}
			}

			UInt32 oldval_utype = utype;
			Property prop_utype = pdatas[28];
			if(prop_utype.isBase())
			{
				if(inited && !inWorld)
					onUtypeChanged(oldval_utype);
			}
			else
			{
				if(inWorld)
				{
					if(prop_utype.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onUtypeChanged(oldval_utype);
					}
				}
			}

		}
	}
}